query Library {
  library {
    id
    name
    address
    books {
      id
      title
      description
      totalPages
      rent
      isRented
      author {
        id
        name
      }
    }
  }
}
