query Library {
    library {
        id
        name
        address
        books {
            id
            title
            author {
                id
                name
            }
        }
    }
}